### PR TITLE
Adds more extensive options for svc type LoadBalancer for the zwave ui chart

### PR DESCRIPTION
**Pull request by wagnst**
LoadBalancer type allows additional values for loadBalancerIP (setting the desired LB IP) as well as externalTrafficPolicy.

### CODE REVIEW

**Comment by wagnst** [comment]
@varet80 would be great if you could have a look and merge if ok.
My `values.yaml` for this case would look like:

```
zwave-js-ui:

  service:
    type: LoadBalancer
    loadBalancerIP: 172.18.1.225
    externalTrafficPolicy: Local
```

**Review by varet80 — APPROVED** [review]

**Comment by varet80** [comment]
Thank you @wagnst.
I added you as contributor, you can create branches directly to repo! and also make the testing/merging easier

**Comment by wagnst** [comment]
> Thank you @wagnst. I added you as contributor, you can create branches directly to repo! and also make the testing/merging easier

i've just re-released the latest tag so this can be used, hope that is fine!

**Comment by varet80** [comment]
All good!

**Pull request merged**
